#include <Extractors/PatExtractor/interface/SuperBaseExtractor.h>

EDM_REGISTER_PLUGINFACTORY(PatExtractorExtractorFactory, "PatExtractorExtractorFactory");
EDM_REGISTER_PLUGINFACTORY(PatExtractorExtractorReadOnlyFactory, "PatExtractorExtractorReadOnlyFactory");
